export const DETERMINISTIC_MERCHANT_CATEGORIES: Record<string, string> = {
  swiggy: "Food & Dining",
  zomato: "Food & Dining",
  zepto: "Food & Dining",
  blinkit: "Food & Dining",
  bigbasket: "Food & Dining",
  "uber eats": "Food & Dining",
  uber: "Transport",
  ola: "Transport",
  rapido: "Transport",
  irctc: "Transport",
  amazon: "Shopping",
  flipkart: "Shopping",
  myntra: "Shopping",
  netflix: "Entertainment",
  spotify: "Entertainment",
  jio: "Utilities",
  airtel: "Utilities",
  "electricity board": "Utilities",
  salary: "Other",
};
